----Cau 1-----
CREATE TABLE MONHOC(
	MAMON CHAR(10) PRIMARY KEY,
	TENMON VARCHAR(20),
	SOTC INT
)
CREATE TABLE SINHVIEN(
	MASV CHAR(10) PRIMARY KEY,
	HOTEN VARCHAR(20),
	NGAYSINH SMALLDATETIME,
)

CREATE TABLE DIEM(
	MASV CHAR (10) FOREIGN KEY REFERENCES SINHVIEN(MASV),
	MAMON CHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMON),
	DIEMTHI FLOAT,
	PRIMARY KEY(MASV, MAMON)
)

INSERT INTO MONHOC(MAMON, TENMON, SOTC) VALUES (N'MH01', N'TOAN', 3)
INSERT INTO MONHOC(MAMON, TENMON, SOTC) VALUES (N'MH02', N'VAN', 3)
INSERT INTO MONHOC(MAMON, TENMON, SOTC) VALUES (N'MH03', N'ANH', 3)
INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH) VALUES (N'SV01', N'Nguyen Thai An', CAST(N'2002-05-07'AS DATE))
INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH) VALUES (N'SV02', N'Nguyen Van Tien', CAST(N'2002-02-17'AS DATE))
INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH) VALUES (N'SV03', N'Le Minh Thuan', CAST(N'1999-04-21'AS DATE))
INSERT INTO DIEM(MASV, MAMON, DIEMTHI) VALUES (N'SV01', N'MH02', 5)
INSERT INTO DIEM(MASV, MAMON, DIEMTHI) VALUES (N'SV02', N'MH01', 5)
INSERT INTO DIEM(MASV, MAMON, DIEMTHI) VALUES (N'SV03', N'MH03', 5)

SELECT * FROM SINHVIEN
SELECT * FROM MONHOC
SELECT * FROM DIEM

----Cau 2 -----
CREATE FUNCTION sv_diemduoi5 (@tenmh VARCHAR(20))
RETURNS INT
AS
BEGIN
	 DECLARE @dem_sv INT
	 SET @dem_sv = (SELECT COUNT(*)
	 FROM Diem
	WHERE @dem_sv < 5)
	 RETURN @dem_sv
END

SELECT dbo.sv_diemduoi5 ('TOAN')

----Cau 3-----
CREATE PROCEDURE nhapdiem (@masv CHAR(10), @mamon CHAR(10), @diemthi FLOAT)
AS
BEGIN
	INSERT INTO DIEM (MASV, MAMON, DIEMTHI)
	VALUES (@masv, @mamon, @diemthi)
END

EXEC nhapdiem N'SV04', N'MH04', 5

----Cau 4-----
CREATE TRIGGER diem_themsua ON DIEM
FOR INSERT, UPDATE
AS
IF(SELECT DIEMTHI FROM inserted) > 10 AND (SELECT DIEMTHI FROM inserted) < 0
BEGIN
	PRINT N'KHONG CHO PHEP'
	ROLLBACK TRANSACTION
END

INSERT INTO DIEM VALUES ('SV02', 'MH01', '2')

